version: '3.8'

services:
  backend:
    build: ./backend 
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "devops-fullstack-app-db.czmsgaeicut9.us-east-1.rds.amazonaws.com"
      DB_USER: "test"
      DB_PASSWORD: "test1234"
      DB_NAME: "postgres"
      ALLOWED_ORIGINS: "*"
      DB_PORT: "5432"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail * || exit 1"]
      interval: 10s
      retries: 3
      timeout: 5s
    volumes:
      - ./backend_data:/app/data   

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://34.226.68.39:3000/health || exit 1"]
      interval: 10s
      retries: 3
      timeout: 5s
